---
abstract: 'use C<IO::Async> with C<UV>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Async-Loop-UV
provides:
  IO::Async::Loop::UV:
    file: lib/IO/Async/Loop/UV.pm
    version: 0.01
requires:
  IO::Async::Loop: 0.49
  UV: 0.24
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
